name: Comment Lint

permissions:
  actions: read
  pull-requests: write

on:
  workflow_run:
    workflows:
      - Lint Cpp
    types:
      - completed

jobs:
  comment-lint:
    if: ${{ github.repository_owner == 'oven-sh' }}
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Download Comment
        uses: actions/download-artifact@v4
        with:
          name: format.log
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: PR Number
        uses: actions/download-artifact@v4
        with:
          name: pr-number.txt
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Setup Environment
        id: env
        shell: bash
        run: |
          # Copy to outputs
          echo "pr-number=$(<pr-number.txt)" >> $GITHUB_OUTPUT
          echo "text_output=$(<format.log)" >> $GITHUB_OUTPUT

      - name: Find Comment
        id: comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ steps.env.outputs.pr-number }}
          comment-author: github-actions[bot]
          body-includes: <!-- generated-comment workflow=${{ github.workflow }} -->
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v4
        if: github.event.workflow_run.conclusion != 'success'
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          issue-number: ${{ steps.env.outputs.pr-number }}
          body: |
            @${{ github.actor }}, C++ linting failed!

            Logs:
            ```cpp
            ${{ steps.env.outputs.text_output }}
            ```

            <!-- generated-comment workflow=${{ github.workflow }} -->
          edit-mode: replace
      - name: Update Previous Comment
        uses: peter-evans/create-or-update-comment@v4
        if: github.event.workflow_run.conclusion == 'success' && steps.comment.outputs.comment-id != ''
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          issue-number: ${{ steps.env.outputs.pr-number }}
          body: |
            @${{ github.actor }}, C++ lint errors fixed! Thank you.

            <!-- generated-comment workflow=${{ github.workflow }} -->
          edit-mode: replace
