name: Lint Cpp

permissions:
  contents: read
  actions: write

env:
  LLVM_VERSION: 16

on:
  workflow_call:
    inputs:
      pr-number:
        type: number
        required: true

jobs:
  lint-cpp:
    name: Lint C++
    runs-on: ${{ github.repository_owner == 'oven-sh' && 'namespace-profile-bun-ci-darwin-aarch64' || 'macos-12' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: latest
      - name: Install Dependencies
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew install \
            llvm@${{ env.LLVM_VERSION }} \
            ninja \
            coreutils \
            openssl@1.1 \
            libiconv \
            gnu-sed --force --overwrite
          echo "$(brew --prefix coreutils)/libexec/gnubin" >> $GITHUB_PATH
          echo "$(brew --prefix llvm@$LLVM_VERSION)/bin" >> $GITHUB_PATH
          brew link --overwrite llvm@$LLVM_VERSION
      - name: Bun install
        run: |
          bun install
      - name: Format
        id: format
        env:
          CPU_TARGET: native
        run: |
          ./run-tidy.sh
      - name: Upload format.log
        if: steps.format.outputs.did_fail == '1'
        uses: actions/upload-artifact@v2
        with:
          name: format.log
          path: format.log
      - name: Upload PR
        if: steps.format.outputs.did_fail == '1'
        uses: actions/upload-artifact@v2
        with:
          name: pr-number.txt
          path: pr-number.txt
      - name: Fail the build
        if: steps.format.outputs.did_fail == '1'
        run: exit 1
