name: Lint Cpp

permissions:
  contents: read
  actions: write
  pull-requests: read

env:
  LLVM_VERSION: 16

on:
  workflow_call:

jobs:
  lint-cpp:
    name: Lint C++
    runs-on: ${{ github.repository_owner == 'oven-sh' && 'namespace-profile-bun-ci-darwin-aarch64' || 'macos-12' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: latest
      - name: Install Dependencies
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew install \
            llvm@${{ env.LLVM_VERSION }} \
            ninja \
            coreutils \
            openssl@1.1 \
            libiconv \
            gnu-sed --force --overwrite
          echo "$(brew --prefix coreutils)/libexec/gnubin" >> $GITHUB_PATH
          echo "$(brew --prefix llvm@$LLVM_VERSION)/bin" >> $GITHUB_PATH
          brew link --overwrite llvm@$LLVM_VERSION
      - name: Bun install
        run: |
          bun install
      - name: Format
        id: format
        env:
          CPU_TARGET: native
        run: |
          rm -f did_fail format.log
          echo 'wow such fail' > format.log
          echo 1 > did_fail
          # bun build:tidy &2>1 | tee format.log || echo 1 > did_fail
          # Upload format.log as github artifact for the workflow
          echo "text_output=$(cat format.log || echo 0)" >> "$GITHUB_OUTPUT"
          echo "did_fail=$(cat did_fail || echo 0)" >> "$GITHUB_OUTPUT"
          echo ${{ github.event.pull_request.number }} > pr-number.txt
      - name: Upload format.log
        if: steps.format.outputs.did_fail == '1'
        uses: actions/upload-artifact@v2
        with:
          name: format.log
          path: format.log
      - name: Upload PR
        if: steps.format.outputs.did_fail == '1'
        uses: actions/upload-artifact@v2
        with:
          name: pr-number.txt
          path: pr-number.txt
      - name: Fail the build
        if: steps.format.outputs.did_fail == '1'
        run: exit 1
