name: autofix.ci # Must be named this for autofix.ci to work

on:
  workflow_call:
    inputs:
      zig-version:
        type: string
        required: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src
            packages
            test
            bench
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: "1.0.21"
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@c7b6cdd3adba8f8b96984640ff172c37c93f73ee
        with:
          version: ${{ inputs.zig-version }}
      - name: Install Dependencies
        run: |
          bun install
      - name: Format
        run: |
          bun fmt
      - name: Format Zig
        run: |
          bun fmt:zig
      - name: Commit # https://autofix.ci/
        uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
